### ISSUE TITLE
Setup CI/CD Pipeline to Deploy Convex

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/survive-the-night-sim#6]
When a pull request is merged into the project, we need to kick off a github action to run a convex deploy.

Here is an example of how I did it on another project.

```
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Deploy Convex
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
        run: npx convex deploy
```

use this, modify it, and get it working on our project
